function(project_install_target)
	install(TARGETS ${PROJECT_NAME}
		EXPORT ${PROJECT_ROOT_NAME}-config
		LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
		ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
		RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
	)
endfunction()
